### ISSUE TITLE
Basic units of measurement for Weight (Mass)

### ISSUE THREAD

**Issue by jordanbrauer** [jordanbrauer/unit-converter#5]
`namespace UnitConverter\Unit\Weight;`

* [x] Gram = `g`
* [x] Kilogram = `kg`
* [x] Metric Tonne = `t`
* [x] Miligram = `mg`
* [x] Newton = `N` _(based on the gravity of Earth)_
* [x] Ounce = `oz`
* [x] Pound = `lb`
* [x] Stone = `st` (thanks @teunw #37)
* [x] UK Long Ton = `ukt` (thanks @teunw #37)
* [x] US Short Ton = `ust` (thanks @teunw #37)
